apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-depl

spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: webapp
      # version: "1"
  replicas: 1


  template:
    metadata:
      labels:
        app: webapp
        # version: "1"
    spec:
      containers:
      - name: webapp-v1
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"