apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  # select the appropriate pod
  selector:
    app: webapp
    # version: "1"

  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
