apiVersion: v1
kind: Pod
metadata:
  name: activemq
  labels:
    app: activemq
spec:
  containers:
  - name: activemq
    image: richardchesterwood/k8s-fleetman-queue:release1
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "2"
