apiVersion: v1
kind: Pod
metadata:
  name: webapp-v1

  labels:
    app: webapp
    version: "1"
spec:
  containers:
  - name: webapp-v1
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"